#
# SPDX-License-Identifier: BSD-2-Clause
#

FROM opensuse/tumbleweed

PREFIXEDLABEL org.opencontainers.image.description="Mixed Test 3"
PREFIXEDLABEL org.opencontainers.image.version="4"

CMD [ "/bin/bash" ]
