# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

package Cavil::Notice;
use Mojo::Base -base, -signatures;

use Cavil::Util        qw(license_text spdx_identifiers spdx_only_expression);
use IO::Compress::Gzip qw($GzipError);
use Mojo::File         qw(path);
use Mojo::Util         qw(encode scope_guard);

use constant RULE  => '=' x 78;
use constant MINOR => '-' x 78;

has 'app';

sub generate_to_file ($self, $id, $file) {
  path($file)->remove if -e $file;

  my $app     = $self->app;
  my $reports = $app->reports;
  my $pkg     = $app->pg->db->select('bot_packages', ['name', 'checkout_dir'], {id => $id})->hash;
  my $version = ($reports->specfile_report($id)->{main} || {})->{version};

  my $tmp_file = "$file.tmp";
  my $cleanup  = scope_guard sub { -e $tmp_file && path($tmp_file)->remove };
  my $handle   = IO::Compress::Gzip->new($tmp_file) or die qq{Can't create NOTICE "$tmp_file": $GzipError};

  # The gzip layer takes bytes, and everything written here is characters
  my $out = sub (@text) { $handle->print(encode('UTF-8', join '', @text)) };

  my $licenses = $reports->licenses_present($id);
  my $terms    = _terms($app->patterns, $licenses);

  _header($out, $pkg, $version);
  _completeness($out, $licenses, $terms);

  # Nothing is collected in memory: the cursor and the section list share a collation, so both are walked
  # once. Terms are written at the close because the notices above them arrive a row at a time.
  my (%written, $open, $noticed);
  my $index = 0;
  my $close = sub () {
    return unless defined $open;
    _terms_of($out, $open, $terms, \%written);
    $open = undef;
  };
  my $begin = sub ($license) {
    $close->();
    ($open, $noticed) = ($license, 0);
    _heading($out, RULE, $license);
  };
  my $upto = sub ($license) {
    while ($index < @$licenses && (!defined $license || $licenses->[$index] lt $license)) {
      $begin->($licenses->[$index++]);
    }
  };

  $reports->each_licensed_copyright(
    $id, 0,
    sub ($license, $copyright) {
      if (!defined $open || $open ne $license) {
        $upto->($license);
        $index++ if $index < @$licenses && $licenses->[$index] eq $license;
        $begin->($license);
      }
      $out->("\n") unless $noticed;
      $noticed = 1;
      $out->("$copyright\n");
    }
  );
  $upto->(undef);
  $close->();

  _unattributed($out, $reports, $id);

  $handle->close;
  path($tmp_file)->move_to($file);
}

sub _header ($out, $pkg, $version) {
  my $name = $pkg->{name};
  $name .= " $version" if defined $version && length $version;
  $out->("NOTICE for $name\n", "Generated by Cavil @{[Cavil->VERSION]} from source checkout $pkg->{checkout_dir}.\n");
}

# First, so nobody reaches the terms without knowing which are missing
sub _completeness ($out, $licenses, $terms) {
  _heading($out, RULE, 'Completeness');
  return $out->("\nCavil detected no licenses in this package.\n") unless @$licenses;

  my @gaps = grep { !$terms->{$_}{complete} } @$licenses;
  $out->(
    "\n",
    'This document reproduces the license text Cavil holds for ',
    scalar(@$licenses) - scalar(@gaps),
    ' of the ', scalar(@$licenses), " licenses detected in this package.\n"
  );
  return unless @gaps;

  $out->("\nNo license text could be resolved for:\n\n");
  $out->("  * $_ ($terms->{$_}{gap})\n") for @gaps;
  $out->("\nThese must be resolved by hand before this document is shipped.\n");
}

sub _heading ($out, $rule, $title) { $out->("\n", $rule, "\n$title\n", $rule, "\n") }

# Blank lines separate the parts rather than trailing them, so every block ends on exactly one newline and
# the space before the next heading is the heading's own
sub _terms_of ($out, $license, $terms, $written) {
  for my $part (@{$terms->{$license}{parts}}) {
    my ($atom, $text) = @$part;
    $out->("\n");

    # A package carrying three GPL variants would otherwise ship the same 35kB three times over
    if (my $seen = $written->{$atom}) {
      $out->("$atom: see the $seen section above.\n");
      next;
    }
    $written->{$atom} = $license;

    $out->(_indent($text));
  }
}

sub _unattributed ($out, $reports, $id) {
  my $first = 1;
  $reports->each_unlicensed_copyright(
    $id, 0,
    sub ($copyright) {
      if ($first) { _heading($out, MINOR, 'Notices not attributable to a specific license'); $out->("\n") }
      $first = 0;
      $out->("$copyright\n");
    }
  );
}

# Verbatim or not at all: what a match happened to cover is evidence, and printing it here would count a
# fragment as a resolved license
sub _terms ($patterns, $licenses) {
  my $curated = $patterns->full_license_texts($licenses);

  my %terms;
  for my $license (@$licenses) {
    my @parts;

    # An expression needs every identifier it names, exceptions included
    my $atoms = spdx_identifiers($license);
    for my $atom (@$atoms) {
      next unless defined(my $text = license_text($atom));
      push @parts, [$atom, $text];
    }

    # The identifiers have to be the whole expression: printing MIT alone for "MIT AND Vendor-Thing-1.0"
    # leaves half the terms out
    my $complete = @$atoms && @parts == @$atoms && spdx_only_expression($license);

    # A text curated against the whole expression is authoritative where the identifiers fall short
    if (!$complete && defined $curated->{$license}) {
      @parts    = ([$license, $curated->{$license}]);
      $complete = 1;
    }

    my $gap
      = @parts  ? 'only part of the expression could be resolved'
      : @$atoms ? 'no bundled text for the identifier'
      :           'no SPDX identifier, no full text curated';
    $terms{$license} = {parts => \@parts, complete => $complete, gap => $gap};
  }

  return \%terms;
}

sub _indent ($text) {
  $text =~ s/^(?=.)/  /mg;
  return $text =~ /\n\z/ ? $text : "$text\n";
}

1;
