# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

use Mojo::Base -strict, -signatures;

use FindBin;
use lib "$FindBin::Bin/lib";

use Test::More;
use Test::Mojo;
use Cavil::Test;
use Cavil::Checkout;
use Cavil::Notice;
use Mojo::File             qw(tempfile);
use Mojo::Util             qw(decode);
use IO::Uncompress::Gunzip qw(gunzip $GunzipError);

plan skip_all => 'set TEST_ONLINE to enable this test' unless $ENV{TEST_ONLINE};

my $cavil_test = Cavil::Test->new(online => $ENV{TEST_ONLINE}, schema => 'notice_test');
my $t          = Test::Mojo->new(Cavil => $cavil_test->default_config);
$cavil_test->spdx_fixtures($t->app);

$t->app->minion->enqueue(unpack => [1]);
$t->app->minion->perform_jobs;

# Generate a NOTICE with whatever data is currently set, and hand back its text
sub gen ($id = 1) {
  my $file = tempfile;
  Cavil::Notice->new(app => $t->app)->generate_to_file($id, "$file");
  gunzip("$file" => \my $buffer) or die "gunzip failed: $GunzipError";
  return decode('UTF-8', $buffer);
}

# The body of one "====" delimited section, so an assertion about a section cannot be satisfied by text
# that happens to sit in a different one
sub section ($notice, $title) {
  my @parts = split /^={70,}\n/m, $notice;
  for my $i (0 .. $#parts) {
    next unless $parts[$i] =~ /\A\Q$title\E\n\z/;
    return $parts[$i + 1] // '';
  }
  return undef;
}

subtest 'Header names the package it covers' => sub {
  my $notice = gen();
  like $notice, qr/^NOTICE for perl-Mojolicious 7\.25\n/,                'the package and its version';
  like $notice, qr/^Generated by Cavil \S+ from source checkout \w+\./m, 'the tool and the evidence it read';
};

subtest 'Notices are grouped under the licenses of the files they came from' => sub {
  my $notice = gen();
  my $apache = section($notice, 'Apache-2.0');
  ok defined $apache, 'the package has an Apache-2.0 section';

  like $apache, qr/^Copyright \(C\) 2008-2017, Sebastian Riedel and others\.$/m, 'a notice from a matched file';
  like $apache, qr/^Copyright \(C\) 2006 Google Inc\.$/m,                        'and another';

  # The whole point of the grouping: whoever redistributes has to retain these *and* the terms
  like $apache, qr/Copyright \(C\) 2013 Google Inc\..*Apache License.*TERMS AND CONDITIONS/s,
    'the terms follow the notices they cover';

  # Sorted, so two runs of the same data cannot disagree about the order
  my @notices = $apache =~ /^(Copyright \(C\) .+)$/mg;
  is_deeply [sort { $a cmp $b } @notices], \@notices, 'notices are sorted within a section';
};

subtest 'A license Cavil knows by name only falls back to the text it matched' => sub {
  my $notice = gen();
  my $custom = section($notice, 'SUSE-NotALicense');
  ok defined $custom, 'the custom license has a section of its own';

  # Not canonical terms, so the document says where it read them instead of presenting them as the license
  like $custom, qr{^SUSE-NotALicense, as found at Mojolicious-7\.25/\S+#L\d+-L\d+:$}m, 'cited to a file and lines';
};

subtest 'Notices no license could be attributed to are kept, not dropped' => sub {
  my $notice = gen();
  my ($tail) = $notice =~ /^-{70,}\nNotices not attributable to a specific license\n-{70,}\n(.*)\z/ms;
  ok defined $tail, 'the remainder has a section of its own';
  like $tail, qr/^Copyright \(c\) 2000-2006, The Perl Foundation\.$/m, 'a notice from a file with no license match';
  like $tail, qr/^Copyright \(c\) 2017 SUSE LINUX GmbH, Nuernberg, Germany\.$/m, 'and another';
};

subtest 'Completeness is stated up front' => sub {
  my $notice = gen();
  like $notice, qr/^This document reproduces the license text Cavil holds for 2 of the 2 licenses/m,
    'both licenses resolved';
  unlike $notice, qr/No license text could be resolved/, 'so nothing is listed as missing';

  # The completeness section comes before any terms, so it cannot be missed by somebody who stops reading
  ok index($notice, 'Completeness') < index($notice, 'Apache License'), 'and it precedes the license text';
};

subtest 'An identifier with no bundled text is named as a gap' => sub {
  $t->app->pg->db->query(q{UPDATE license_patterns SET spdx = 'Nope-1.0' WHERE license = 'Apache-2.0'});
  my $notice = gen();

  like $notice, qr/^This document reproduces the license text Cavil holds for 1 of the 2 licenses/m, 'one short';
  like $notice, qr/^  \* Nope-1\.0 \(no SPDX identifier, no license document found\)$/m, 'named, with the reason';
  like $notice, qr/^These must be resolved by hand before this document is shipped\.$/m, 'and what to do about it';

  # Still gets a section, so its notices are retained even though its terms could not be
  ok defined section($notice, 'Nope-1.0'), 'the license is still a section';

  $t->app->pg->db->query(q{UPDATE license_patterns SET spdx = 'Apache-2.0' WHERE license = 'Apache-2.0'});
};

# A second license naming an identifier the first one already reproduced. Without this the GPL family
# alone would put 100kB of near-identical text into a document meant to be read.
subtest 'A license text is reproduced once, however many expressions name it' => sub {
  $t->app->pg->db->query(q{UPDATE license_patterns SET spdx = 'MIT OR Apache-2.0' WHERE license = 'SUSE-NotALicense'});
  my $notice = gen();

  my $both = section($notice, 'MIT OR Apache-2.0');
  ok defined $both, 'the expression has a section of its own';
  like $both, qr/Permission is hereby granted, free of charge/, 'reproducing the identifier nothing else named';

  # "Apache-2.0" sorts first and so is where the text lands
  is scalar(() = $notice =~ /TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION/g), 1,
    'the Apache text appears exactly once';
  like $both, qr/^Apache-2\.0: see the Apache-2\.0 section above\.$/m, 'and the second mention points at it';

  $t->app->pg->db->query(q{UPDATE license_patterns SET spdx = '' WHERE license = 'SUSE-NotALicense'});
};

subtest 'An exception is reproduced alongside the license it modifies' => sub {
  $t->app->pg->db->query(
    q{UPDATE license_patterns SET spdx = 'GPL-2.0-only WITH Autoconf-exception-2.0' WHERE license = 'Apache-2.0'});
  my $notice = gen();

  my $with = section($notice, 'GPL-2.0-only WITH Autoconf-exception-2.0');
  ok defined $with, 'the expression has a section';
  like $with, qr/GNU GENERAL PUBLIC LICENSE/,                            'the license text is there';
  like $with, qr/Autoconf Configure Script Exception|configure script/i, 'and so is the exception text';

  $t->app->pg->db->query(q{UPDATE license_patterns SET spdx = 'Apache-2.0' WHERE license = 'Apache-2.0'});
};

# The terms for a license Cavil knows by name only are read out of the file the match was made in, and the
# indexer matched against the post-processed copy. Markup stripping is the hard case: HTML::Parser reports
# the source line of each text run, and the translation replays the same stripper rather than storing a
# map, so the citation has to name the line of the original file, not of the copy that was scanned.
subtest 'Evidence is read from the original file, through the post-processing that shifted it' => sub {
  my $id = $cavil_test->spdx_line_shift_fixtures($t->app);
  $t->app->minion->enqueue(unpack => [$id]);
  $t->app->minion->perform_jobs;
  is $t->app->minion->jobs({states => ['failed']})->total, 0, 'no failed jobs';

  # The row Cavil::Model::Reports::license_evidence hands a generator, for the markup-stripped file
  my $row = $t->app->pg->db->query(
    "SELECT mf.filename, pm.sline, pm.eline FROM pattern_matches pm JOIN matched_files mf ON mf.id = pm.file
      WHERE pm.package = ? AND mf.filename LIKE '%page%'", $id
  )->hash;
  is $row->{filename}, 'page.processed.html', 'the indexer scanned the stripped copy';
  is $row->{sline},    2,                     'and recorded the declaration on its line 2';

  my $dir = $t->app->packages->pkg_checkout_dir($id);
  my ($text, $where) = Cavil::Checkout->new($dir)->evidence_text($row);
  is $where, 'page.html#L6-L6', 'the citation names the original file and its own line 6';
  like $text, qr/Permission is hereby granted under the Cavil Fixture License/, 'and quotes what is there';

  # Which is where the declaration actually sits, markup and all
  my $line = (split /\n/, $dir->child('.unpacked', 'page.html')->slurp)[5];
  like $line, qr/Permission is hereby granted under the Cavil Fixture License/, 'line 6 of the original';

  # The wrapped (non-markup) path shifts too, and has to translate the same way
  my $js = $t->app->pg->db->query(
    "SELECT mf.filename, pm.sline, pm.eline FROM pattern_matches pm JOIN matched_files mf ON mf.id = pm.file
      WHERE pm.package = ? AND mf.filename LIKE '%bundle%'", $id
  )->hash;
  is $js->{sline}, 5, 'the line-wrapper pushed the declaration down one line';
  my (undef, $js_where) = Cavil::Checkout->new($dir)->evidence_text($js);
  is $js_where, 'bundle.js#L4-L4', 'which the citation undoes';
};

# Every derived document sits beside the checkout, so a re-unpack walks straight over it. A NOTICE is
# worse than an SBOM here: unpacking decompresses a file of pure license text back into the tree, and the
# next index reads every line of it as package content.
subtest 'A re-unpack does not feed the documents back into the index' => sub {
  $t->app->packages->generate_documents(1);
  $t->app->minion->perform_jobs;
  my $dir = $t->app->packages->pkg_checkout_dir(1);
  ok -f $dir->child('.report.notice.txt.gz'), 'the NOTICE is cached beside the checkout';


  $t->app->minion->enqueue(unpack => [1]);
  $t->app->minion->perform_jobs;
  is $t->app->minion->jobs({states => ['failed']})->total, 0, 'no failed jobs';

  my %indexed = map { $_->[0] => 1 } @{Cavil::Checkout->new($dir)->unpacked_files};
  is_deeply [grep {/^\.report\./} sort keys %indexed], [], 'nothing derived is offered to the indexer';
  ok !-e $dir->child('.unpacked', '.report.notice.txt'), 'and the NOTICE was never unpacked in the first place';

};

subtest 'The same data produces the same document' => sub {
  is gen(), gen(), 'generating twice is byte identical';
};

done_testing;
